# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2    
updates:
  - directory: /
    package-ecosystem: nuget
    ignore:
      - dependency-name: BepInEx.Core
      - dependency-name: HarmonyX
      - dependency-name: UnityEngine.Modules
    schedule:
      interval: daily
    groups:
      silksong-libraries:
        patterns:
          - Silksong.*
        exclude-patterns:
          - Silksong.GameLibs 
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
    groups:
      artifacts:
        patterns:
          - actions/upload-artifact
          - actions/download-artifact
